import { Router, Request, Response } from "express";
import jwt from "jsonwebtoken";

const router = Router();

interface MealPlan {
  _id: string;
  userId: string;
  healthProfileId: string;
  title: string;
  aiModel: string;
  days: {
    day: number;
    title: string;
    theme: string;
    macros: {
      protein: number;
      carbs: number;
      fat: number;
    };
    totalCalories: number;
    meals: {
      mealType: string;
      name: string;
      description: string;
      ingredients: string[];
      benefits: string[];
      calories: number;
      macros: {
        protein: number;
        carbs: number;
        fat: number;
      };
    }[];
    tips: string[];
  }[];
  prompt: string;
  rawAiResponse: string;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

const mealPlans: Map<string, MealPlan> = new Map();

// Middleware to extract userId from JWT token
const extractUserIdFromToken = (token: string): string | null => {
  try {
    const secret = process.env.JWT_SECRET || "supersecret_change_me";
    const decoded = jwt.verify(token, secret) as {
      userId?: string;
      id?: string;
    };
    return decoded.userId || decoded.id || null;
  } catch (error) {
    return null;
  }
};

// Mock meal plan data - in production, this would be generated by AI
function generateMockMealPlan(): MealPlan {
  const id = Math.random().toString(36).substring(7);
  const now = new Date().toISOString();

  return {
    _id: id,
    userId: "",
    healthProfileId: "",
    title: "7-Day Personalized Meal Plan",
    aiModel: "lm-studio",
    days: [
      {
        day: 1,
        title: "Day 1",
        theme: "Balanced nutrition & energy",
        macros: {
          protein: 110,
          carbs: 220,
          fat: 70,
        },
        totalCalories: 2000,
        meals: [
          {
            mealType: "breakfast",
            name: "Oatmeal with Berries",
            description: "Steel-cut oats with fresh berries and honey",
            ingredients: [
              "Oats",
              "Blueberries",
              "Strawberries",
              "Honey",
              "Milk",
            ],
            benefits: [
              "High in fiber",
              "Antioxidants from berries",
              "Sustained energy",
            ],
            calories: 450,
            macros: {
              protein: 15,
              carbs: 65,
              fat: 12,
            },
          },
          {
            mealType: "lunch",
            name: "Grilled Chicken Salad",
            description:
              "Grilled chicken breast with mixed greens and olive oil dressing",
            ingredients: [
              "Chicken breast",
              "Mixed greens",
              "Cherry tomatoes",
              "Cucumber",
              "Olive oil",
            ],
            benefits: ["Lean protein", "Rich in vitamins", "Low in calories"],
            calories: 520,
            macros: {
              protein: 45,
              carbs: 20,
              fat: 18,
            },
          },
          {
            mealType: "dinner",
            name: "Salmon with Roasted Vegetables",
            description: "Baked salmon fillet with seasonal roasted vegetables",
            ingredients: [
              "Salmon fillet",
              "Broccoli",
              "Bell peppers",
              "Zucchini",
              "Olive oil",
            ],
            benefits: [
              "Omega-3 fatty acids",
              "Vitamin D",
              "Mineral-rich vegetables",
            ],
            calories: 650,
            macros: {
              protein: 50,
              carbs: 30,
              fat: 40,
            },
          },
        ],
        tips: [
          "Drink plenty of water throughout the day",
          "Include colorful vegetables for maximum nutrition",
          "Prepare meals in advance for better consistency",
        ],
      },
      {
        day: 2,
        title: "Day 2",
        theme: "Mediterranean diet focus",
        macros: {
          protein: 115,
          carbs: 230,
          fat: 65,
        },
        totalCalories: 2050,
        meals: [
          {
            mealType: "breakfast",
            name: "Greek Yogurt Bowl",
            description: "Greek yogurt with granola and fresh fruit",
            ingredients: [
              "Greek yogurt",
              "Granola",
              "Mixed berries",
              "Honey",
              "Almonds",
            ],
            benefits: [
              "Probiotics for gut health",
              "High protein",
              "Calcium-rich",
            ],
            calories: 420,
            macros: {
              protein: 20,
              carbs: 58,
              fat: 12,
            },
          },
          {
            mealType: "lunch",
            name: "Mediterranean Pasta",
            description:
              "Whole wheat pasta with olive oil, tomatoes, and fresh basil",
            ingredients: [
              "Whole wheat pasta",
              "Tomatoes",
              "Basil",
              "Olive oil",
              "Garlic",
            ],
            benefits: ["Complex carbs", "Antioxidants", "Heart-healthy fats"],
            calories: 480,
            macros: {
              protein: 18,
              carbs: 72,
              fat: 14,
            },
          },
          {
            mealType: "dinner",
            name: "Herb-Roasted Chicken",
            description: "Herb-roasted chicken with sweet potato and greens",
            ingredients: [
              "Chicken breast",
              "Sweet potato",
              "Spinach",
              "Fresh herbs",
              "Olive oil",
            ],
            benefits: ["Lean protein", "Complex carbs", "Iron and vitamins"],
            calories: 600,
            macros: {
              protein: 55,
              carbs: 60,
              fat: 20,
            },
          },
        ],
        tips: [
          "Use fresh herbs to enhance flavor without extra calories",
          "Opt for whole grain versions of pasta and bread",
          "Mediterranean diet emphasizes healthy fats from olive oil",
        ],
      },
    ],
    prompt: "Generate a personalized meal plan based on user health profile",
    rawAiResponse: "{}",
    notes: null,
    createdAt: now,
    updatedAt: now,
  };
}

// POST /meal-plans/generate - Generate meal plan
router.post("/generate", (req: Request, res: Response) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const token = authHeader.substring(7);
    const userId = extractUserIdFromToken(token);

    if (!userId) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    // Generate mock meal plan
    const mealPlan = generateMockMealPlan();
    mealPlan.userId = userId;
    mealPlan.healthProfileId = Math.random().toString(36).substring(7);

    // Store meal plan
    mealPlans.set(mealPlan._id, mealPlan);

    return res.status(201).json({
      ok: true,
      message: "Meal plan generated successfully",
      mealPlan,
    });
  } catch (error) {
    console.error("Error generating meal plan:", error);
    return res.status(500).json({
      message: "Failed to generate meal plan",
    });
  }
});

// GET /meal-plans/latest - Get latest meal plan for user
router.get("/latest", (req: Request, res: Response) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const token = authHeader.substring(7);
    const userId = extractUserIdFromToken(token);

    if (!userId) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const userMealPlans = Array.from(mealPlans.values())
      .filter((p) => p.userId === userId)
      .sort(
        (a, b) =>
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
      );

    if (userMealPlans.length === 0) {
      return res.status(404).json({ message: "Meal plan not found" });
    }

    return res.status(200).json(userMealPlans[0]);
  } catch (error) {
    console.error("Error fetching latest meal plan:", error);
    return res.status(500).json({
      message: "An error occurred",
    });
  }
});

// GET /meal-plans - Get all meal plans for user with pagination
router.get("/", (req: Request, res: Response) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const token = authHeader.substring(7);
    const userId = extractUserIdFromToken(token);

    if (!userId) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const limit = parseInt(req.query.limit as string) || 10;
    const skip = parseInt(req.query.skip as string) || 0;

    const userMealPlans = Array.from(mealPlans.values())
      .filter((p) => p.userId === userId)
      .sort(
        (a, b) =>
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
      );

    const paginatedPlans = userMealPlans.slice(skip, skip + limit);

    return res.status(200).json({
      mealPlans: paginatedPlans,
      total: userMealPlans.length,
      limit,
      skip,
    });
  } catch (error) {
    console.error("Error fetching meal plans:", error);
    return res.status(500).json({
      message: "An error occurred",
    });
  }
});

// DELETE /meal-plans/:id - Delete a meal plan
router.delete("/:id", (req: Request, res: Response) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const token = authHeader.substring(7);
    const userId = extractUserIdFromToken(token);

    if (!userId) {
      return res.status(401).json({ message: "Unauthorized" });
    }

    const mealPlanId = req.params.id;
    const mealPlan = mealPlans.get(mealPlanId);

    if (!mealPlan || mealPlan.userId !== userId) {
      return res.status(404).json({ message: "Meal plan not found" });
    }

    mealPlans.delete(mealPlanId);

    return res.status(200).json({ ok: true });
  } catch (error) {
    console.error("Error deleting meal plan:", error);
    return res.status(500).json({
      message: "An error occurred",
    });
  }
});

export default router;
